### PR TITLE
fix: Prevent reused Android WebView crash

### LINKED ISSUE #21954: IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
Sentry Issue: [JETPACK-ANDROID-1994](https://a8c.sentry.io/issues/6624010943/?referrer=github_integration)

```
IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    at org.wordpress.android.editor.gutenberg.GutenbergKitEditorFragment.onCreateView(GutenbergKitEditorFragment.java:152)
...
(66 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by dcalhoun**
## What?

Prevent crash originating from setting a duplicative parent on the editor
WebView.

## Why?

Fix CMM-496. Fix https://github.com/wordpress-mobile/WordPress-Android/issues/21954. The crash is disruptive.

## How?

Setting an additional parent to the WebView results in a crash. Therefore, we
avoid this scenario by first removing the parent.

## Testing Instructions

I was unable to reproduce the crash naturally, but forced the scenario with a
little help from AI. Temporarily applying the following patches and toggling the
parent removal will showcase how the crash occurs and is addressed by the
changed. 

The editor will not load fully with the testing patches applied.

<details><summary>GutenbergKit patch</summary>

```diff
diff --git a/android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt b/android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt
index 8631e69..e8689d6 100644
--- a/android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt
+++ b/android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt
@@ -558,7 +558,8 @@ object GutenbergWebViewPool {
         } else {
             val parent = preloadedWebView!!.parent
             if (parent != null) {
-                (parent as? android.view.ViewGroup)?.removeView(preloadedWebView!!)
+                // TODO: Reinstate to prevent the crash
+                // (parent as? android.view.ViewGroup)?.removeView(preloadedWebView!!)
             }
         }
         return preloadedWebView!!
@@ -579,6 +580,29 @@ object GutenbergWebViewPool {
         webView.destroy()
         preloadedWebView = null
     }
+
+    // Temporary test method to verify the fix
+    @JvmStatic
+    fun testWebViewReuse(context: Context) {
+        Log.d("GutenbergWebViewPool", "=== Testing WebView Reuse ===")
+
+        // Get first webview
+        val webView1 = getPreloadedWebView(context)
+        Log.d("GutenbergWebViewPool", "First webview: ${webView1.hashCode()}")
+
+        // Simulate adding to parent
+        val parent = android.widget.FrameLayout(context)
+        parent.addView(webView1)
+        Log.d("GutenbergWebViewPool", "Added to parent: ${webView1.parent != null}")
+
+        // Get second webview (should be same instance)
+        val webView2 = getPreloadedWebView(context)
+        Log.d("GutenbergWebViewPool", "Second webview: ${webView2.hashCode()}")
+        Log.d("GutenbergWebViewPool", "Same instance: ${webView1 == webView2}")
+        Log.d("GutenbergWebViewPool", "Has parent: ${webView2.parent != null}")
+
+        Log.d("GutenbergWebViewPool", "=== Test Complete ===")
+    }
 }
 
 data class Media(

```

</details>

<details><summary>WP-Android patch</summary>

```diff
diff --git a/libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java b/libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java
index 4686f4d3b79..408b23f847d 100644
--- a/libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java
+++ b/libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java
@@ -582,6 +582,7 @@ public class GutenbergKitEditorFragment extends EditorFragmentAbstract implement
                 .build();
 
         mGutenbergView.start(config);
+        GutenbergWebViewPool.testWebViewReuse(getContext());
     }
 
     @Override

```

</details>

### Accessibility Testing Instructions

N/A, no user facing changes.

## Screenshots or screencast 
N/A, no user facing changes.

### CODE REVIEW

File: android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt [hunk 1]
```diff
@@ -555,6 +555,11 @@ object GutenbergWebViewPool {
     fun getPreloadedWebView(context: Context): GutenbergView {
         if (preloadedWebView == null) {
             preloadedWebView = createAndPreloadWebView(context)
+        } else {
+            val parent = preloadedWebView!!.parent
+            if (parent != null) {
+                (parent as? android.view.ViewGroup)?.removeView(preloadedWebView!!)
+            }
         }
```
Comment (adalpari) [inline android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt]:
```suggestion
        val currentView = preloadedWebView
        if (currentView == null) {
            preloadedWebView = createAndPreloadWebView(context)
        } else {
            (currentView.parent as? android.view.ViewGroup)?.removeView(currentView)
        }
```

Just a bit more Kotlin way. So, we remove the `!!` operators and also simplify the conditionals.
(Note this has been written as pseudocode)

File: android/Gutenberg/src/test/java/org/wordpress/gutenberg/GutenbergWebViewPoolTest.kt [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+import org.junit.Before
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.mockito.Mock
+import org.mockito.MockitoAnnotations
+import org.robolectric.RobolectricTestRunner
+import org.robolectric.RuntimeEnvironment
+
+@RunWith(RobolectricTestRunner::class)
+class GutenbergWebViewPoolTest {
```
Comment (adalpari) [inline android/Gutenberg/src/test/java/org/wordpress/gutenberg/GutenbergWebViewPoolTest.kt:18]: Kudos for the tests!

**Review by adalpari — APPROVED** [review]
LGTM!
Just left a minor comment about syntax, but feel free to ignore it.

File: android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt (hunk 1 above)
Comment (dcalhoun) [reply android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt]: Thanks for the guidance! Addressed in https://github.com/wordpress-mobile/GutenbergKit/pull/152/commits/b4d3438498fad3de77120f814e4770471982ac03.
