### PR TITLE
fix: Catch null content errors

### LINKED ISSUE #74: JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject
Sentry Issue: [JETPACK-ANDROID-15D7](https://a8c.sentry.io/issues/6262654655/?referrer=github_integration)

```
RuntimeException: java.lang.reflect.InvocationTargetException
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

InvocationTargetException: None
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject
    at org.json.JSON.typeMismatch(JSON.java:112)
    at org.json.JSONObject.<init>(JSONObject.java:172)
    at org.json.JSONObject.<init>(JSONObject.java:185)
    at org.wordpress.gutenberg.GutenbergView.getTitleAndContent$lambda$1$lambda$0(GutenbergView.kt:288)
    at org.wordpress.gutenberg.GutenbergView.$r8$lambda$TD_G-NCvLSEG475q-U77UCHabQ8(GutenbergView.kt:0)
...
(12 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by dcalhoun**
Related: 

* https://github.com/wordpress-mobile/GutenbergKit/issues/74
* https://github.com/wordpress-mobile/WordPress-Android/pull/21673

## What?

Prevent editor crashes caused by null content values.

## Why?

Fix https://github.com/wordpress-mobile/GutenbergKit/issues/74. The crashes are disruptive.

## How?

There are contexts where the JavaScript runtime appears to send null
values to the host app. It could be performance related, but we should
catch the errors nonetheless.

## Testing Instructions

Test saving title and content changes in the editor—save/update button, back button, quit app, etc. 

### Accessibility Testing Instructions

N/A, no user-facing changes.

## Screenshots or screencast 
N/A, no user-facing changes.

### CODE REVIEW

File: android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt [hunk 1]
```diff
@@ -314,17 +314,22 @@ class GutenbergView : WebView {
...
-                callback.onResult(lastUpdatedTitle, lastUpdatedContent)
+                try {
+                    val jsonObject = JSONObject(result)
+                    lastUpdatedTitle = jsonObject.getString("title")
+                    lastUpdatedContent = jsonObject.getString("content")
+                } catch (e: JSONException) {
+                    Log.e("GutenbergView", "Received invalid JSON from editor.getTitleAndContent")
+                }
+
+                callback.onResult(lastUpdatedTitle ?: "", lastUpdatedContent ?: originalContent)
```
Comment (dcalhoun) [inline android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt:332]: There is a possibility where this unexpected resets the editor's title or content to an empty string, effectively discarding a user's content. This is, obviously, not ideal, but seems to be an existing issue for all the editors. 

The approach was implemented previously—see a [related comment](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3177#issuecomment-1881441653)— to improve editor stability. There remains opportunity to improve the stability and avoid losing user content. I'd like to considering addressing that a separate matter from preventing crashes.

File: android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt [hunk 2]
```diff
@@ -362,11 +367,7 @@ class GutenbergView : WebView {
 
     @JavascriptInterface
     fun onEditorContentChanged() {
-        getTitleAndContent(object : TitleAndContentCallback {
-            override fun onResult(title: String, content: String) {
-                contentChangeListener?.onContentChanged()
-            }
-        }, false)
```
Comment (dcalhoun) [inline android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt:369]: This may have been utilized at one point, but I perceive this `getTitleAndContent` invocation is unnecessary now. The `getTitleAndContent` method is invoked when the host app chooses to persist the latest changes on a set interval (in response to the broadcasted content change event).

File: android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt [hunk 3]
```diff
@@ -41,8 +41,8 @@ class GutenbergView : WebView {
     private var siteApiRoot: String = ""
     private var siteApiNamespace: String = ""
     private var authHeader: String = ""
-    private var lastUpdatedTitle = ""
-    private var lastUpdatedContent = ""
+    private var lastUpdatedTitle: CharSequence? = null
```
Comment (dcalhoun) [inline android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt:44]: Using `CharSequence` matches the WP-Android implementation for other editors. Using a nullable valuable simplifies conditional logic within `getTitleAndContent`.

**Review by nbradbury — APPROVED** [review]
Changes are good! :shipit:
